'use client';

import { FormEvent, useCallback, useEffect, useRef, useState } from 'react';

type Message = { id: string; text: string; userId: string; createdAt: string; user: { name: string } };

export default function DirectRoom({ userId, otherUserId }: { userId: string; otherUserId: string }) {
  const [messages, setMessages] = useState<Message[]>([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [sending, setSending] = useState(false); const bottom = useRef<HTMLDivElement>(null);
  const load = useCallback(async () => { try { const response = await fetch(`/api/direct/${otherUserId}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not load messages.'); setMessages(data.messages); setError(''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load messages.'); } finally { setLoading(false); } }, [otherUserId]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 4000); return () => window.clearInterval(timer); }, [load]);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages]);
  async function send(event: FormEvent) { event.preventDefault(); if (!text.trim() || sending) return; setSending(true); setError(''); try { const response = await fetch(`/api/direct/${otherUserId}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Could not send message.'); setText(''); setMessages(current => [...current, data.message]); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not send message.'); } finally { setSending(false); } }
  return <div className="chat-room direct-room"><div className="messages-area">{loading && <p className="text-center text-muted">Loading…</p>}{!loading && !messages.length && <div className="chat-welcome"><div className="chat-welcome-icon">✦</div><h2>Start the conversation</h2><p>You are friends, so you can message privately here.</p></div>}{messages.map(message => <div className={`message-row ${message.userId === userId ? 'mine' : 'theirs'}`} key={message.id}>{message.userId !== userId && <span className="sender-name"><span className="sender-avatar">{message.user.name.slice(0, 1).toUpperCase()}</span>{message.user.name}</span>}<div className={`bubble ${message.userId === userId ? 'bubble-mine' : 'bubble-theirs'}`}>{message.text}</div><span className="timestamp">{new Date(message.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span></div>)}<div ref={bottom} /></div>{error && <p className="composer-error" role="alert">{error}</p>}<form className="input-area" onSubmit={send}><input className="chat-input" aria-label="Message" maxLength={1000} value={text} onChange={event => setText(event.target.value)} placeholder="Type a message…" disabled={sending} /><button className="chat-send" type="submit" disabled={!text.trim() || sending} aria-label="Send message">{sending ? '…' : '↑'}</button></form></div>;
}
